# Generated by Django 2.0.7 on 2019-07-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField(auto_created=True, unique=True)),
                ('course_title', models.CharField(max_length=80)),
                ('course_description', models.CharField(max_length=10000)),
                ('course_created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_number', models.IntegerField(auto_created=True)),
                ('course_assignmentID', models.IntegerField(auto_created=True, unique=True)),
                ('assignment_name', models.CharField(max_length=80)),
                ('assignment_description', models.CharField(max_length=10000)),
                ('assignment_due_date', models.DateField()),
                ('assignment_created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(auto_created=True, unique=True)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_cell', models.IntegerField()),
                ('user_pic', models.URLField()),
                ('user_created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_activityID', models.IntegerField(auto_created=True, unique=True)),
                ('activity_details', models.CharField(max_length=10000)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Activity_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_activity_typeID', models.IntegerField(auto_created=True, unique=True)),
                ('student_activity_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Course_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_course_assignmentID', models.IntegerField(auto_created=True, unique=True)),
                ('start_date', models.DateField()),
                ('complete_date', models.DateField(blank=True)),
                ('isStarted', models.BooleanField(default=0)),
                ('stu_course_asgn_created_date', models.DateField(auto_now=True)),
                ('related_assignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.Course_Assignment')),
                ('related_courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.Course')),
                ('related_studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.IUser')),
            ],
        ),
        migrations.AddField(
            model_name='student_activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.Student_Activity_Type'),
        ),
        migrations.AddField(
            model_name='student_activity',
            name='related_studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.IUser'),
        ),
        migrations.AddField(
            model_name='student_activity',
            name='related_student_course_assignmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.Student_Course_Assignment'),
        ),
        migrations.AddField(
            model_name='course_assignment',
            name='assignment_inkosi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.IUser'),
        ),
        migrations.AddField(
            model_name='course_assignment',
            name='related_courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkosi2_dpa.IUser'),
        ),
    ]
