# Generated by Django 2.0.7 on 2019-07-13 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inkosi2_dpa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_assignment',
            name='assignment_inkosi',
        ),
        migrations.AddField(
            model_name='course_assignment',
            name='assignment_created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Couse_Assignment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course_assignment',
            name='assignment_created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='iuser',
            name='user_created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student_activity',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student_course_assignment',
            name='stu_course_asgn_created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
